steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - scheduler/Dockerfile
      - -t
      - asia-southeast1-docker.pkg.dev/cpo-prediction/cpo-scheduler/scheduler:latest
      - .
images:
  - asia-southeast1-docker.pkg.dev/cpo-prediction/cpo-scheduler/scheduler:latest
options:
  logging: CLOUD_LOGGING_ONLY
