# Generated by Django 5.2.9 on 2025-12-17 15:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketState",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, unique=True, verbose_name="Tanggal"
                    ),
                ),
                (
                    "state",
                    models.IntegerField(
                        choices=[(0, "Bearish"), (1, "Bullish"), (2, "Neutral")],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(2),
                        ],
                        verbose_name="Market State",
                    ),
                ),
                (
                    "probability",
                    models.FloatField(
                        help_text="Confidence level of the predicted state",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Probabilitas",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Market State",
                "verbose_name_plural": "Market States",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="web_markets_date_9d88da_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True, verbose_name="Tanggal Publikasi"
                    ),
                ),
                ("title", models.TextField(verbose_name="Judul Berita")),
                ("snippet", models.TextField(verbose_name="Cuplikan Berita")),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Range: -1 (Negative) to 1 (Positive)",
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name="Skor Sentimen",
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("Positive", "Positive"),
                            ("Negative", "Negative"),
                            ("Neutral", "Neutral"),
                        ],
                        max_length=10,
                        verbose_name="Label Sentimen",
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL Berita")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="web_news_date_e6bf72_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, unique=True, verbose_name="Tanggal"
                    ),
                ),
                ("open", models.FloatField(verbose_name="Harga Pembukaan")),
                ("high", models.FloatField(verbose_name="Harga Tertinggi")),
                ("low", models.FloatField(verbose_name="Harga Terendah")),
                ("close", models.FloatField(verbose_name="Harga Penutupan")),
                (
                    "volume",
                    models.FloatField(blank=True, null=True, verbose_name="Volume"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price Histories",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["-date"], name="web_pricehi_date_cd98ef_idx")
                ],
            },
        ),
    ]
